version: '2'

services:

    snappass:
        build: .
        image: icelantic/icepass
        ports:
            - "80:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=False
        depends_on:
          - redis

    redis:
        image: "redis:latest"
